### PR TITLE
update travis rules

### PR DESCRIPTION
**Pull request by jnavila**

### CODE REVIEW

**Comment by hedrok** [comment]
Please confirm that everything is completed.
I'm not merging now in case you're going to add some other changes to this PR.

**Comment by jnavila** [comment]
It should be ok. The real test is when the PR is merged into master :wink:

**Comment by hedrok** [comment]
:)

**Comment by jnavila** [comment]
There it is! https://github.com/progit/progit2-uk/releases/tag/2.1.0

**Comment by hedrok** [comment]
Hooray! :)

But still no pdf/epub links here: https://git-scm.com/book/uk/v2 like in English version... Can we do something about it?..

As I understand such releases are created automatically on each commit to master?..

**Comment by jnavila** [comment]
The update to git-scm is a daily crontab, so it should be set up in at most one day.

The release can only be done on tags. Right now all the new push to master will tag the latest commit and generate a release.

I plan to add the detection of a flag  [norelease] in the commits'message to prevent automatic tagging. But most of the time, you want to release automatically after a merge of a PR.

**Comment by hedrok** [comment]
Ok, thank you very much, I'm closing the issue.

**Pull request merged**
